"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var am_general;
(function (am_general) {
    var Type;
    (function (Type) {
        Type[Type["DEVICE_REBOOT"] = 0] = "DEVICE_REBOOT";
        Type[Type["APPLICATION_RESTART"] = 1] = "APPLICATION_RESTART";
        Type[Type["CAPTURE_SCREENSHOT"] = 2] = "CAPTURE_SCREENSHOT";
        Type[Type["PLAYLIST_UPDATE"] = 3] = "PLAYLIST_UPDATE";
        Type[Type["MONITORING"] = 4] = "MONITORING";
        Type[Type["PLAYER_FILES_UPDATE"] = 5] = "PLAYER_FILES_UPDATE";
        Type[Type["FORCE_HOTSPOT_MODE"] = 6] = "FORCE_HOTSPOT_MODE";
        Type[Type["FORCE_UPGRADE"] = 7] = "FORCE_UPGRADE";
        Type[Type["MEDIA_PLAY"] = 8] = "MEDIA_PLAY";
        Type[Type["UPLOAD_ACTIVITY_LOGS"] = 9] = "UPLOAD_ACTIVITY_LOGS";
        Type[Type["UPLOAD_SETTINGS_FILES"] = 10] = "UPLOAD_SETTINGS_FILES";
        Type[Type["VOTE_PLAYLIST_ITEM"] = 11] = "VOTE_PLAYLIST_ITEM";
        Type[Type["GET_VOTED_ITEMS"] = 12] = "GET_VOTED_ITEMS";
        Type[Type["STATISTICS_FILES_UPLOAD"] = 13] = "STATISTICS_FILES_UPLOAD";
        Type[Type["PLAYBACK_ACTION"] = 14] = "PLAYBACK_ACTION";
        Type[Type["ENABLE_NOW_PLAYING_REPORTING"] = 15] = "ENABLE_NOW_PLAYING_REPORTING";
        Type[Type["MEDIA_VOLUME_UP"] = 16] = "MEDIA_VOLUME_UP";
        Type[Type["MEDIA_VOLUME_DOWN"] = 17] = "MEDIA_VOLUME_DOWN";
        Type[Type["MEDIA_VOLUME_SET"] = 18] = "MEDIA_VOLUME_SET";
        Type[Type["SOFTWARE_EA_SET"] = 19] = "SOFTWARE_EA_SET";
        Type[Type["CONNECTED_TO_SERVER"] = 20] = "CONNECTED_TO_SERVER";
        Type[Type["BLOCKED_MUSIC_UPDATED"] = 21] = "BLOCKED_MUSIC_UPDATED";
        Type[Type["MEDIA_VOLUME_GET"] = 22] = "MEDIA_VOLUME_GET";
        Type[Type["URL_CONNECTION_TEST"] = 23] = "URL_CONNECTION_TEST";
        Type[Type["SETTINGS_UPDATED"] = 24] = "SETTINGS_UPDATED";
        Type[Type["ON_DEMAND_EVENT_PLAY"] = 25] = "ON_DEMAND_EVENT_PLAY";
        Type[Type["EVENT_STOP"] = 26] = "EVENT_STOP";
        Type[Type["PURGE_FILES"] = 27] = "PURGE_FILES";
        Type[Type["VOLUME_PERCENT_FACTOR_ZONE_LEFT_SET"] = 28] = "VOLUME_PERCENT_FACTOR_ZONE_LEFT_SET";
        Type[Type["VOLUME_PERCENT_FACTOR_ZONE_RIGHT_SET"] = 29] = "VOLUME_PERCENT_FACTOR_ZONE_RIGHT_SET";
        Type[Type["SELECT_MUSIC_PLAYLIST"] = 30] = "SELECT_MUSIC_PLAYLIST";
        Type[Type["UPLOAD_STORAGE_FILES_LIST"] = 31] = "UPLOAD_STORAGE_FILES_LIST";
        Type[Type["UPLOAD_STORAGE_FILES"] = 32] = "UPLOAD_STORAGE_FILES";
        Type[Type["UPLOAD_INSTALLED_APPLICATIONS_LIST"] = 33] = "UPLOAD_INSTALLED_APPLICATIONS_LIST";
    })(Type = am_general.Type || (am_general.Type = {}));
})(am_general = exports.am_general || (exports.am_general = {}));
//# sourceMappingURL=AE_ServerCommand.js.map